app:
  replicas: 2
  env: stage
  container:
    image: azureacrae.azurecr.io/ecom-mda-frontend/frontend:v0.8.0
  computerc:
    requests:
      cpu: 1
      memory: 2Gi
    limits:
      cpu: 1
      memory: 2Gi

hpa: 
  enabled: true 
  minReplicas: 2
  maxReplicas: 4
  cpuUtilizationPercentage: 90

  
config:
  data:
    PORT: "8080"
    PRODUCT_CATALOG_SERVICE_ADDR: "productcatalogservice:3550"
    CURRENCY_SERVICE_ADDR: "currencyservice:7000"
    CART_SERVICE_ADDR: "cartservice:7070"
    RECOMMENDATION_SERVICE_ADDR: "recommendationservice:8080"
    SHIPPING_SERVICE_ADDR: "shippingservice:50051"
    CHECKOUT_SERVICE_ADDR: "checkoutservice:5050"
    AD_SERVICE_ADDR: "adservice:9555"
    ENABLE_PROFILER: "0"
  
