apiVersion: v1
kind: ConfigMap
metadata:
  name: ecom-mda-frontend
  labels:
    {{- include "ecom-mda-frontend.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.config.data | nindent 2}}
  # Uncomment and modify the following lines as needed
  # ENV_PLATFORM: "aws"
  # CYMBAL_BRANDING: "true"
  # FRONTEND_MESSAGE: "Replace this with a message you want to display on all pages."
