apiVersion: v1
kind: Service
metadata:
  name: ecom-mda-frontend-svc
  labels:
  {{- include "ecom-mda-frontend.labels" . | nindent 4}}
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '8080'
spec:
  type: ClusterIP
  selector:
    app: ecom-mda-ui
  ports:
  - name: http
    port: 80
    targetPort: 8080


